### ISSUE TITLE
Screensharing

### ISSUE THREAD

**Issue by zeke** [vitorgalvao/appear.in#5]
Screensharing with appear.in requires a browser extension, right?

It would be cool if you could vendor that extension into this app somehow.

cc @marshallofsound, who wrote this thing: https://github.com/MarshallOfSound/electron-devtools-installer

**Comment by vitorgalvao** [comment]
> Screensharing with appear.in requires a browser extension, right?

That is correct.

> It would be cool if you could vendor that extension into this app somehow.

It was my understanding that I cannot (hence never really tried). Since screen sharing can even act on the whole screen (not just the browser), some browser APIs must be in use. While searching for it at the time, https://github.com/electron/electron/issues/1498#issuecomment-96995155 and https://github.com/electron/electron/issues/250#issuecomment-69299158 made me think it wouldn’t be possible in this case.

> cc @marshallofsound, who wrote this thing: https://github.com/MarshallOfSound/electron-devtools-installer

Indeed, if there’s a way I’d be interested.

**Comment by vitorgalvao** [comment]
No new developments here, so I’m closing. This feature is something I’d like as well, so if there’s a way, I’d be interested.

**Comment by Ajeey** [comment]
Any updates on this? Can we use the screen share extension within the app?

**Comment by vitorgalvao** [comment]
@Ajeey As explained multiple times already, this is a limitation with Electron. There’s nothing I can do.

You need to complain on their tracker.
